include:
  - project: 'devops/templates'
    file: 'base.yml'

deploy_tag:
  stage: deploy
  tags:
    - docker
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=${CI_COMMIT_TAG} "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  environment: production

deploy_branch:
  stage: deploy
  tags:
    - docker
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data branch=main "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  environment: production